steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -t us-west2-docker.pkg.dev/workers-on-gcp/workers-on-gcp-repo/workers-on-gcp-image:tag1 .
    automapSubstitutions: true
images:
  - "us-west2-docker.pkg.dev/workers-on-gcp/workers-on-gcp-repo/workers-on-gcp-image:tag1"
